### PR TITLE
added practical 1 ana martins

### PR DESCRIPTION
**Pull request by anaismartins**

### CODE REVIEW

**Comment by anaismartins** [comment]
apparently windows removes the .DS_Store files automatically? so i committed the deleting of them accidentaly

**Comment by gerkovink** [comment]
> apparently windows removes the .DS_Store files automatically? so i committed the deleting of them accidentaly

Not a problem at all. The `.DS_Store` files are redundant on Windows, anyways.

**Review by gerkovink — APPROVED** [review]
thanks.

**Comment by anaismartins** [comment]
do the commits we make after the first pull request (before it's accepted) make it to the same pull request? i cannot find how to open another pull request but maybe that's not a thing?

**Review by gerkovink — APPROVED** [review]

**Comment by gerkovink** [comment]
@anaismartins congrats on your first PR. Thanks to everyone for structuring your work as a group.

**Pull request merged**
